# Generated by Django 4.2.5 on 2023-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='year',
            field=models.FloatField(default='2000'),
        ),
    ]
